# Cloudflare Pages configuration
name = "page"

# Specify the directory to deploy
pages_build_output_dir = "./out"

# Function configuration
[functions]
directory = "functions"
node_compat = true

# Compatibility date
compatibility_date = "2024-05-27"
